#!/bin/bash
#ALTER NO FOUND - 

# CREATE CARPETA /bin/alx && rm /bin

# Moded creado por @Phreaker56
echo -e "ESPERE UN MOMENTO"
[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || apt-get install curl -y &>/dev/null
sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/phreaker56/Multi-Script/main/ChumoGH-PLUS/instalalib.sh)"
